version: "3.3"

services:

  api:
    image: ghcr.io/doxciai/doxci-api:vzs2
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - redis

  upload-api:
    image: ghcr.io/doxciai/doxci-upload-api:vzs2
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: --requirepass ${REDIS_PASSWORD}